#!/bin/sh

#  if no user configuration
if [ ! -d ~/.xmonad ]; then
    # display the manpage
    xterm -e "man xmonad" &
    # and the README
    xterm -e "less /usr/share/doc/xmonad*/README.fedora" &

    # try to configure for a gnome session
    if [ "$DESKTOP_SESSION" = "xmonad-gnome" ]; then
	if ghc-pkg latest xmonad-contrib >/dev/null; then
	    mkdir ~/.xmonad
	    cat > ~/.xmonad/xmonad.hs <<EOF
import XMonad
import XMonad.Config.Gnome

main = xmonad gnomeConfig
EOF
	else
	    echo "xmonad-start: install ghc-xmonad-contrib-devel for GNOME support"
	fi
    fi
fi

if [ -r ~/.xmonad/session ]; then
    sh ~/.xmonad/session
fi

xmonad
