#!/bin/sh

#  if no user configuration
if [ ! -d ~/.xmonad ]; then
    # add a desktop friendly config if possible
    if [ -r /usr/share/xmonad/xmonad.hs ]; then
	mkdir ~/.xmonad
	cp -p /usr/share/xmonad/xmonad.hs ~/.xmonad
    else
	echo "xmonad-start: install xmonad-config to customize"
    fi
    # display the manpage
    case $DESKTOP_SESSION in
	xmonad-gnome) TERM_CMD="gnome-terminal -x" ;;
	*) TERM_CMD="xterm -e" ;;
    esac
    (sleep 5; $TERM_CMD man xmonad) &
fi

if [ -r ~/.xmonad/session ]; then
    sh ~/.xmonad/session
fi

xmonad
